// Code generated by entc, DO NOT EDIT.

package assignment

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the assignment type in the database.
	Label = "assignment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIsExam holds the string denoting the is_exam field in the database.
	FieldIsExam = "is_exam"
	// FieldDueDate holds the string denoting the due_date field in the database.
	FieldDueDate = "due_date"
	// FieldDuration holds the string denoting the duration field in the database.
	FieldDuration = "duration"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// Table holds the table name of the assignment in the database.
	Table = "assignments"
)

// Columns holds all SQL columns for assignment fields.
var Columns = []string{
	FieldID,
	FieldIsExam,
	FieldDueDate,
	FieldDuration,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsExam holds the default value on creation for the "is_exam" field.
	DefaultIsExam bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
