// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"strconv"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/google/uuid"
	"github.com/msal4/entgql/ent/assignment"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"github.com/vmihailenco/msgpack/v5"
)

// OrderDirection defines the directions in which to order a list of items.
type OrderDirection string

const (
	// OrderDirectionAsc specifies an ascending order.
	OrderDirectionAsc OrderDirection = "ASC"
	// OrderDirectionDesc specifies a descending order.
	OrderDirectionDesc OrderDirection = "DESC"
)

// Validate the order direction value.
func (o OrderDirection) Validate() error {
	if o != OrderDirectionAsc && o != OrderDirectionDesc {
		return fmt.Errorf("%s is not a valid OrderDirection", o)
	}
	return nil
}

// String implements fmt.Stringer interface.
func (o OrderDirection) String() string {
	return string(o)
}

// MarshalGQL implements graphql.Marshaler interface.
func (o OrderDirection) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(o.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (o *OrderDirection) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("order direction %T must be a string", val)
	}
	*o = OrderDirection(str)
	return o.Validate()
}

func (o OrderDirection) reverse() OrderDirection {
	if o == OrderDirectionDesc {
		return OrderDirectionAsc
	}
	return OrderDirectionDesc
}

func (o OrderDirection) orderFunc(field string) OrderFunc {
	if o == OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

func cursorsToPredicates(direction OrderDirection, after, before *Cursor, field, idField string) []func(s *sql.Selector) {
	var predicates []func(s *sql.Selector)
	if after != nil {
		if after.Value != nil {
			var predicate func([]string, ...interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.CompositeGT
			} else {
				predicate = sql.CompositeLT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.Columns(field, idField),
					after.Value, after.ID,
				))
			})
		} else {
			var predicate func(string, interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.GT
			} else {
				predicate = sql.LT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.C(idField),
					after.ID,
				))
			})
		}
	}
	if before != nil {
		if before.Value != nil {
			var predicate func([]string, ...interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.CompositeLT
			} else {
				predicate = sql.CompositeGT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.Columns(field, idField),
					before.Value, before.ID,
				))
			})
		} else {
			var predicate func(string, interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.LT
			} else {
				predicate = sql.GT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.C(idField),
					before.ID,
				))
			})
		}
	}
	return predicates
}

// PageInfo of a connection type.
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *Cursor `json:"startCursor"`
	EndCursor       *Cursor `json:"endCursor"`
}

// Cursor of an edge type.
type Cursor struct {
	ID    uuid.UUID `msgpack:"i"`
	Value Value     `msgpack:"v,omitempty"`
}

// MarshalGQL implements graphql.Marshaler interface.
func (c Cursor) MarshalGQL(w io.Writer) {
	quote := []byte{'"'}
	w.Write(quote)
	defer w.Write(quote)
	wc := base64.NewEncoder(base64.RawStdEncoding, w)
	defer wc.Close()
	_ = msgpack.NewEncoder(wc).Encode(c)
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (c *Cursor) UnmarshalGQL(v interface{}) error {
	s, ok := v.(string)
	if !ok {
		return fmt.Errorf("%T is not a string", v)
	}
	if err := msgpack.NewDecoder(
		base64.NewDecoder(
			base64.RawStdEncoding,
			strings.NewReader(s),
		),
	).Decode(c); err != nil {
		return fmt.Errorf("cannot decode cursor: %w", err)
	}
	return nil
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func getCollectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	oc := graphql.GetOperationContext(ctx)
	field := fc.Field

walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Name == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return getCollectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

// AssignmentEdge is the edge representation of Assignment.
type AssignmentEdge struct {
	Node   *Assignment `json:"node"`
	Cursor Cursor      `json:"cursor"`
}

// AssignmentConnection is the connection containing edges to Assignment.
type AssignmentConnection struct {
	Edges      []*AssignmentEdge `json:"edges"`
	PageInfo   PageInfo          `json:"pageInfo"`
	TotalCount int               `json:"totalCount"`
}

// AssignmentPaginateOption enables pagination customization.
type AssignmentPaginateOption func(*assignmentPager) error

// WithAssignmentOrder configures pagination ordering.
func WithAssignmentOrder(order *AssignmentOrder) AssignmentPaginateOption {
	if order == nil {
		order = DefaultAssignmentOrder
	}
	o := *order
	return func(pager *assignmentPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultAssignmentOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithAssignmentFilter configures pagination filter.
func WithAssignmentFilter(filter func(*AssignmentQuery) (*AssignmentQuery, error)) AssignmentPaginateOption {
	return func(pager *assignmentPager) error {
		if filter == nil {
			return errors.New("AssignmentQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type assignmentPager struct {
	order  *AssignmentOrder
	filter func(*AssignmentQuery) (*AssignmentQuery, error)
}

func newAssignmentPager(opts []AssignmentPaginateOption) (*assignmentPager, error) {
	pager := &assignmentPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultAssignmentOrder
	}
	return pager, nil
}

func (p *assignmentPager) applyFilter(query *AssignmentQuery) (*AssignmentQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *assignmentPager) toCursor(a *Assignment) Cursor {
	return p.order.Field.toCursor(a)
}

func (p *assignmentPager) applyCursors(query *AssignmentQuery, after, before *Cursor) *AssignmentQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultAssignmentOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *assignmentPager) applyOrder(query *AssignmentQuery, reverse bool) *AssignmentQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultAssignmentOrder.Field {
		query = query.Order(direction.orderFunc(DefaultAssignmentOrder.Field.field))
	}
	return query
}

// Paginate executes the query and returns a relay based cursor connection to Assignment.
func (a *AssignmentQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...AssignmentPaginateOption,
) (*AssignmentConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newAssignmentPager(opts)
	if err != nil {
		return nil, err
	}

	if a, err = pager.applyFilter(a); err != nil {
		return nil, err
	}

	conn := &AssignmentConnection{Edges: []*AssignmentEdge{}}
	if !hasCollectedField(ctx, edgesField) || first != nil && *first == 0 || last != nil && *last == 0 {
		if hasCollectedField(ctx, totalCountField) ||
			hasCollectedField(ctx, pageInfoField) {
			count, err := a.Count(ctx)
			if err != nil {
				return nil, err
			}
			conn.TotalCount = count
			conn.PageInfo.HasNextPage = first != nil && count > 0
			conn.PageInfo.HasPreviousPage = last != nil && count > 0
		}
		return conn, nil
	}

	if (after != nil || first != nil || before != nil || last != nil) && hasCollectedField(ctx, totalCountField) {
		count, err := a.Clone().Count(ctx)
		if err != nil {
			return nil, err
		}
		conn.TotalCount = count
	}

	a = pager.applyCursors(a, after, before)
	a = pager.applyOrder(a, last != nil)
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	if limit > 0 {
		a = a.Limit(limit)
	}

	if field := getCollectedField(ctx, edgesField, nodeField); field != nil {
		a = a.collectField(graphql.GetOperationContext(ctx), *field)
	}

	nodes, err := a.All(ctx)
	if err != nil || len(nodes) == 0 {
		return conn, err
	}

	if len(nodes) == limit {
		conn.PageInfo.HasNextPage = first != nil
		conn.PageInfo.HasPreviousPage = last != nil
		nodes = nodes[:len(nodes)-1]
	}

	var nodeAt func(int) *Assignment
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Assignment {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Assignment {
			return nodes[i]
		}
	}

	conn.Edges = make([]*AssignmentEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		conn.Edges[i] = &AssignmentEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}

	conn.PageInfo.StartCursor = &conn.Edges[0].Cursor
	conn.PageInfo.EndCursor = &conn.Edges[len(conn.Edges)-1].Cursor
	if conn.TotalCount == 0 {
		conn.TotalCount = len(nodes)
	}

	return conn, nil
}

var (
	// AssignmentOrderFieldDueDate orders Assignment by due_date.
	AssignmentOrderFieldDueDate = &AssignmentOrderField{
		field: assignment.FieldDueDate,
		toCursor: func(a *Assignment) Cursor {
			return Cursor{
				ID:    a.ID,
				Value: a.DueDate,
			}
		},
	}
	// AssignmentOrderFieldDuration orders Assignment by duration.
	AssignmentOrderFieldDuration = &AssignmentOrderField{
		field: assignment.FieldDuration,
		toCursor: func(a *Assignment) Cursor {
			return Cursor{
				ID:    a.ID,
				Value: a.Duration,
			}
		},
	}
)

// String implement fmt.Stringer interface.
func (f AssignmentOrderField) String() string {
	var str string
	switch f.field {
	case assignment.FieldDueDate:
		str = "DUE_DATE"
	case assignment.FieldDuration:
		str = "DURATION"
	}
	return str
}

// MarshalGQL implements graphql.Marshaler interface.
func (f AssignmentOrderField) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(f.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (f *AssignmentOrderField) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("AssignmentOrderField %T must be a string", v)
	}
	switch str {
	case "DUE_DATE":
		*f = *AssignmentOrderFieldDueDate
	case "DURATION":
		*f = *AssignmentOrderFieldDuration
	default:
		return fmt.Errorf("%s is not a valid AssignmentOrderField", str)
	}
	return nil
}

// AssignmentOrderField defines the ordering field of Assignment.
type AssignmentOrderField struct {
	field    string
	toCursor func(*Assignment) Cursor
}

// AssignmentOrder defines the ordering of Assignment.
type AssignmentOrder struct {
	Direction OrderDirection        `json:"direction"`
	Field     *AssignmentOrderField `json:"field"`
}

// DefaultAssignmentOrder is the default ordering of Assignment.
var DefaultAssignmentOrder = &AssignmentOrder{
	Direction: OrderDirectionAsc,
	Field: &AssignmentOrderField{
		field: assignment.FieldID,
		toCursor: func(a *Assignment) Cursor {
			return Cursor{ID: a.ID}
		},
	},
}

// ToEdge converts Assignment into AssignmentEdge.
func (a *Assignment) ToEdge(order *AssignmentOrder) *AssignmentEdge {
	if order == nil {
		order = DefaultAssignmentOrder
	}
	return &AssignmentEdge{
		Node:   a,
		Cursor: order.Field.toCursor(a),
	}
}
