// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/msal4/entgql/ent/assignment"
	"github.com/msal4/entgql/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	assignmentFields := schema.Assignment{}.Fields()
	_ = assignmentFields
	// assignmentDescIsExam is the schema descriptor for is_exam field.
	assignmentDescIsExam := assignmentFields[1].Descriptor()
	// assignment.DefaultIsExam holds the default value on creation for the is_exam field.
	assignment.DefaultIsExam = assignmentDescIsExam.Default.(bool)
	// assignmentDescID is the schema descriptor for id field.
	assignmentDescID := assignmentFields[0].Descriptor()
	// assignment.DefaultID holds the default value on creation for the id field.
	assignment.DefaultID = assignmentDescID.Default.(func() uuid.UUID)
}
