// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Assignment is the predicate function for assignment builders.
type Assignment func(*sql.Selector)
